spring:
  application:
    name: gateway
  config:
    import:
      configserver:http://localhost:8087,optional:jwt.yml



springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: Yabam API
        url: http://localhost:8072/yabam/v3/api-docs

---

# ----- prod 전용 설정 -----
spring:
  config:
    activate:
      on-profile: prod 
  config:
    import:
      configserver:http://192.168.0.171:8888,optional:jwt.yml

