spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8087
  config:
    import:
      configserver:http://localhost:8087,optional:jwt.yml



springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: Yabam API
        url: http://localhost:8072/yabam/v3/api-docs

