spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8087


springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: Yabam API
        url: http://localhost:8072/yabam/v3/api-docs

