version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: pos_module_mysql
    ports:
      - 3314:3306
    environment:
      MYSQL_DATABASE: local-pos-mysql
      MYSQL_CHARSET: utf8mb4
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql
