spring:
  application:
    name: auth

---

# ----- local 전용 설정 -----

spring:
  config:
    activate:
      on-profile: local
    import:
      configserver:http://localhost:8888


---

# ----- dev 전용 설정 -----
spring:
  config:
    activate:
      on-profile: dev
    import:
      configserver:http://192.168.0.171:8888
