spring:
  application:
    name: yabam
  config:
    activate:
      on-profile: local
    import: configserver:http://localhost:8888
  data:
    web:
      pageable:
        one-indexed-parameters: true
---

spring:
  application:
    name: yabam
  config:
    activate:
      on-profile: dev
    import: configserver:http://192.168.0.171:8888,optional:jwt.yml
