version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: kumoh_yabam
    ports:
      - 3315:3306
    environment:
      MYSQL_DATABASE: local_mydb
      MYSQL_CHARSET: utf8mb4
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql
    restart: always  # 자동 재시작 설정
